#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|improvement|hotfix)\-[0-9]+\-[a-z0-9._-]+$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: type-issueNumber-description.
Your commit will be rejected.
You should rename your branch to a valid name and try again.
Types include [feature|bugfix|improvement|hotfix].
If you would like to rename the current branch run git checkout -m <newName>".

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0